import { Component, OnInit } from '@angular/core';
import { EmpService } from '../emp.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-places',
  templateUrl: './places.component.html',
  styleUrls: ['./places.component.css']
})
export class PlacesComponent implements OnInit {
  products:any;
  stateplace:any;
  constructor(private router: Router, private service: EmpService) { 
    this.stateplace = this.service.placecity;
    this.products = [{id:401,imagepath:'assets/janpics/AthirapallyWaterfalls(Thrissur).jpeg',pname:'Athirappilly Waterfalls',
    description:'Athirappilly Falls, is situated in Athirappilly Panchayat in Chalakudy Taluk of Thrissur District in Kerala, India on the Chalakudy River, which originates from the upper reaches of the Western Ghats at the entrance to the Sholayar ranges. It is the largest waterfall in Kerala, which stands tall at 80 feet. Just a short drive from Athirappilly to the Vazhachal falls, which is close to dense green forests that are home to many endangered and endemic species of flora and fauna.Forest wildlife in the area includes the Asiatic elephant, tiger, leopard, bison, sambar, and lion-tailed macaque. The unique 180 metres (590 ft) elevation riparian forest in the Athirappilly-Vazhachal area is the only location where all four South Indian species of hornbills — the great hornbill (the state bird of Kerala), Malabar pied hornbill, Malabar grey hornbill, and the Indian grey hornbill are found living together. If the proposed 163-MW Athirappilly hydroelectric project is built, these unique birds may vanish from these forests because it will submerge the hornbills.The railway station nearest Athirappilly Falls is 30 kilometres (19 mi) to the west in Chalakudi Railway Station, and the nearest airport is Kochi International Airport, about 55 kilometres (34 mi) southwest of the waterfall and 58 kilometres (36 mi) south of City of Thrissur.[5] Athirappilly is easily reachable from Chalakudy and Angamaly by taxi or by bus from the Chalakudy and Angamaly bus terminal. Athirappilly is situated on the highways connecting Tamil Nadu and Kerala, amidst thick forest, so night riding is not advised.',price:'14,000/-'},
    {id:402,imagepath:'assets/janpics/Vadakkunnathan-Temple(Thrissur).jpg',pname:'Vadakkunnathan Temple',
    description:'Vadakkunnathan Temple is an ancient Hindu temple dedicated to Shiva at city of Thrissur, of Kerala state in India. This temple is a classic example of the architectural style of Kerala and has monumental towers on all four sides and also a kuttambalam. Mural paintings depicting various episodes from Mahabharata can be seen inside the temple..[1][2][3] The shrines and the Kuttambalam display vignettes carved in wood. The temple, along with the mural paintings, has been declared as a National Monument by India under the AMASR Act.[4] According to popular local lore, this is the first temple built by Parasurama, the sixth avatar of Vishnu. Thekkinkadu maidan, encircling the Vadakkunnathan Temple, is the main venue of the Thrissur Pooram.The temple was built at the time of Perumthachan from Parayi petta panthirukulam. It is said that Perumthachan lived during the seventh century; so the Koothambalam may be 1,300 years old. According to Malayalam historian V. V. K. Valath, the temple was a pre-Dravidian Kavu (shrine). Later, the temple was influenced by Buddhism, Jainism and Vaishnavism. In the early days, Paramekkavu Bhagavathi was also inside the Vadakkunnathan temple. But Koodalmanikyam Temple, Kodungallur Bhagavathy Temple and Ammathiruvadi Temple, Urakam is older than Vadakkunnathan temple, according to temple documents.[9] It also had influences from Buddhist temples and Jain temples.The temple is situated in an elevated hillock in the centre of Thrissur City and is surrounded by a massive stone wall enclosing an area of nearly 9 acres (36,000 m2). Inside this fortification, there are four gopurams facing four cardinal directions. Between the inner temple and the outer walls, there is a spacious compound, the entrance to which is through gopurams. Of these, the gopurams on the south and north are not open to the public. The public enter either through the east or west gopuram. The inner temple is separated from the outer temple by a broad circular granite wall enclosing a broad corridor called Chuttambalam. Entrance into the inner temple is through a passage through the corridor.',price:'10000/-'},
    {id:403,imagepath:'assets/janpics/ThrissurZoo(Thrissur).png',pname:'Thrissur Zoo and Museum',
    description:'Thrissur Zoo or State Museum & Zoo, Thrissur (formerly the Trichur Zoo) is a 13.5-acre (5.5 ha) zoo that opened in 1885 in a small area called Chembukkavu, in the heart of Thrissur City, Kerala, India. It is one of the oldest zoos in the country, and is home to a wide variety of animals, reptiles, and birds. The zoo compound includes a natural history museum and an art museum that showcase the social and cultural heritage of the region. The Thrissur Zoo is 2 kilometres (1.2 mi) from the Thrissur City center and is open from 10:00 AM till 5:15 PM, except on Mondays. Being one of the two Zoological Parks in the state of Kerala, it sees a lot of visitors on a regular basis. Still and video cameras are allowed in the park for a small fee.Wildlife at the Thrissur zoo includes tigers, lions, deers, sloth bears, monkeys, hippopotamus, camels, cobras, kraits, vipers, rat snakes, pink flamingos, mithun of the north-eastern hills, and lion-tailed macaques. There is also a special building which houses snakes.The zoo includes a Zoological Garden, Botanical Garden, Art Museum, and Natural History Museum in its compound.Two beautiful niches with majestic seating are arranged for senior citizens who can take rest while their children and grandchildren enjoy the sprawling zoo campus.A new home for the zoo is being constructed in nearby Puthur, and will expand the size of the zoo from its current 13.5 acres (5.5 ha) to 306 acres (124 ha). The new zoo will be close to the Peechi Dam, Kerala Forest Research Institute, Kerala Agricultural University College of Forestry, and College of Veterinary and Animal Sciences.',price:'9,541/-'}];
  }
  ngOnInit() {
  }
  addToCart(products: any){
    this.service.addToCart(products);
  }

}
